[[GAP_pkg_orb]]
arch = "aarch64"
git-tree-sha1 = "824194b716a0bf1cbb04befbe9ab52c24c659c61"
os = "macos"

    [[GAP_pkg_orb.download]]
    sha256 = "401e8ad00e631811b305c035ec2c8c1adf64a07cfa481db7e8b377ff4afb7b8b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v501.10000.0+0/GAP_pkg_orb.v501.10000.0.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_orb]]
arch = "aarch64"
git-tree-sha1 = "31cf0c03959aeb043cbe38c607451ecaf3df82e6"
libc = "glibc"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "39ad29ac40dd2154f0325ae1f634cb716e8150fe6e7ea7b0a3d972afd133be4d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v501.10000.0+0/GAP_pkg_orb.v501.10000.0.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_orb]]
arch = "aarch64"
git-tree-sha1 = "5f2aac27cd49e8c571f7040d500351ab5d1498ce"
libc = "musl"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "a714f82c78ca61f9c62b978f4e67de6321668b71afa7e83fddabe0a1ca4ee317"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v501.10000.0+0/GAP_pkg_orb.v501.10000.0.aarch64-linux-musl.tar.gz"
[[GAP_pkg_orb]]
arch = "aarch64"
git-tree-sha1 = "e6448a97b6930a12e16d94628e7bd104485a519b"
os = "freebsd"

    [[GAP_pkg_orb.download]]
    sha256 = "d418ebb30b9ac9df03d99cfa7d53f0a84d70f7997dd21445fc9d8e67842c608f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v501.10000.0+0/GAP_pkg_orb.v501.10000.0.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_orb]]
arch = "powerpc64le"
git-tree-sha1 = "28179fe56e83e39feb9b5c6e64da1931ae567824"
libc = "glibc"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "6489a54afb7578f1b486dbc11cb26d7ecce0d8b706a3412b6f628d5728d02243"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v501.10000.0+0/GAP_pkg_orb.v501.10000.0.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_orb]]
arch = "riscv64"
git-tree-sha1 = "3819a47e260c67d8750fb557b011ac4d109f8d72"
libc = "glibc"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "46af6880831b618c785e594b66c5f312619ef43f710874b5a6c2b480f22ad78a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v501.10000.0+0/GAP_pkg_orb.v501.10000.0.riscv64-linux-gnu.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "c7f44c349f04498225b3abd64aaf3af9207ce4e5"
os = "macos"

    [[GAP_pkg_orb.download]]
    sha256 = "8cf7fd3d631e6ee645a9872e2c93571057055b3caac00e2a38ebd6bd1a163482"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v501.10000.0+0/GAP_pkg_orb.v501.10000.0.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "a5f55d2187c7fe8d284935c6b179bb60df3315df"
libc = "glibc"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "e78b45a45d1f48e53f2a26fa6559ada04d732af567083922d9249ce223f4f0d8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v501.10000.0+0/GAP_pkg_orb.v501.10000.0.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "aeae043576544ecb028ecd510ccfd9d7fcca30d3"
libc = "musl"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "941aa9b9415629d42d9418fd0d3f60be73aaf7731f27a7aa31b14648efd9270b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v501.10000.0+0/GAP_pkg_orb.v501.10000.0.x86_64-linux-musl.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "7bc81f0157d2da0dd9c72c94e8b639549c3cf172"
os = "freebsd"

    [[GAP_pkg_orb.download]]
    sha256 = "4ec8f6c66fdae1af4a4a416f43562685c1357b42ab4121712610ee1cb0d515ab"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v501.10000.0+0/GAP_pkg_orb.v501.10000.0.x86_64-unknown-freebsd.tar.gz"
