[[GAP_pkg_orb]]
arch = "aarch64"
git-tree-sha1 = "dd6640fd17fd436106e32d7528dc9b9b4c630dda"
os = "macos"

    [[GAP_pkg_orb.download]]
    sha256 = "e7f623bbab32ba02efb8fa2249577dddd2899f10445e5712009b8f8c5ac8653f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.800.401+0/GAP_pkg_orb.v400.800.401.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_orb]]
arch = "aarch64"
git-tree-sha1 = "4fbfaee99bda9815a92d0403b88bbbbb9626d618"
libc = "glibc"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "b3c1272f51c5d1c74efac5c0143d54fcdb7bc4b6b3531003c5808aeeee33aa67"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.800.401+0/GAP_pkg_orb.v400.800.401.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_orb]]
arch = "aarch64"
git-tree-sha1 = "8358c04579ed83d08ab28336deb48cfcb5bb7d5f"
libc = "musl"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "cf7ef696e8cfb87bb311160ad90221448f80965a4025b82b352fe01c827e3481"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.800.401+0/GAP_pkg_orb.v400.800.401.aarch64-linux-musl.tar.gz"
[[GAP_pkg_orb]]
arch = "powerpc64le"
git-tree-sha1 = "6898127cc6e24eb7f32ca505e2d050e25bc71afd"
libc = "glibc"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "f7e8c9ae2ec48ccb61aeaf07958bebb193f08b9498be73fd2e535038ee9eca94"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.800.401+0/GAP_pkg_orb.v400.800.401.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "b01aa3a3eb044e6532282dc35133835f40dd585c"
os = "macos"

    [[GAP_pkg_orb.download]]
    sha256 = "5a9110295c1cbd8ee1ec2fa1d53a4b230487c8ceae7c0ccba059e7433f1d8ed9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.800.401+0/GAP_pkg_orb.v400.800.401.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "efd6f469b8a2347327b31bf7c9524174ee29fbae"
libc = "glibc"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "f66a32c7aa997655796dc62e9cce14ba163310891041d1238073e745c24390aa"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.800.401+0/GAP_pkg_orb.v400.800.401.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "e27714df3b13618fb6718a1f5084c09bc222852e"
libc = "musl"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "1fe0d58d651f56e8bddc7b344fd1931a03a09595f77758199ada3ee5af5cf4bd"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.800.401+0/GAP_pkg_orb.v400.800.401.x86_64-linux-musl.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "26458029cf8d6d656cb4b0066f1e69c793b4de4b"
os = "freebsd"

    [[GAP_pkg_orb.download]]
    sha256 = "9b8b15db8639260529ce882d4dcc4d76097bba68c620e8613bcd4adb33a8ed87"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.800.401+0/GAP_pkg_orb.v400.800.401.x86_64-unknown-freebsd.tar.gz"
