[[GAP_pkg_orb]]
arch = "aarch64"
git-tree-sha1 = "9fe09a1cc4c9bc00a683ec7b50bc323882a4821f"
os = "macos"

    [[GAP_pkg_orb.download]]
    sha256 = "e3fedfcba386fb8ba10095b72a299afcf56f8f7991c916455167f322ebd4cc96"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.800.500+0/GAP_pkg_orb.v400.800.500.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_orb]]
arch = "aarch64"
git-tree-sha1 = "11fed122af8c75b91301a6f2f0f0131b5590b68f"
libc = "glibc"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "5fbaaf69894cc33fecf056a7898b616802c3d4d7c7079b57be415fae7ee58b86"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.800.500+0/GAP_pkg_orb.v400.800.500.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_orb]]
arch = "aarch64"
git-tree-sha1 = "e90197f798745d9da6796e3e3116d5c19202a0a5"
libc = "musl"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "2fa65f6a835e2940d946901307bb72769a9ac9bde3b7651c27019f9156e3ea95"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.800.500+0/GAP_pkg_orb.v400.800.500.aarch64-linux-musl.tar.gz"
[[GAP_pkg_orb]]
arch = "powerpc64le"
git-tree-sha1 = "7b33834753d310dad440c0377344c3f960ca169e"
libc = "glibc"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "b8ae950d283ad572766a2296be783003ac930ba213a85a7a5008924ff2602dbc"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.800.500+0/GAP_pkg_orb.v400.800.500.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "65e36daa234bdfeec4882f17d5e74b92302e3ff4"
os = "macos"

    [[GAP_pkg_orb.download]]
    sha256 = "eb396e2ae8b827c088bde6a66bb373fb655459da7df16e301724cb7e52c68444"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.800.500+0/GAP_pkg_orb.v400.800.500.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "1c8dd3ba26a6b1234f2484d9a6eace188557e97b"
libc = "glibc"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "72f0863e5dafa31be7995fa59fd9d9f0b683d3074a63b9c8321d16b44df3082f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.800.500+0/GAP_pkg_orb.v400.800.500.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "120431dd52bb97fa47c243d21e3407a73f81f39a"
libc = "musl"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "adc124552b827639f2a937a4955bdeb10ed0e6918c3de61943c3dff1988a927b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.800.500+0/GAP_pkg_orb.v400.800.500.x86_64-linux-musl.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "2f8ecfd24977ae39ab57cb50c0307554aae8481e"
os = "freebsd"

    [[GAP_pkg_orb.download]]
    sha256 = "42a1561ea5a7b5cf922f39fa56b20fbfdc36af41bb330c1bf53642276e7b471e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.800.500+0/GAP_pkg_orb.v400.800.500.x86_64-unknown-freebsd.tar.gz"
