[[GAP_pkg_orb]]
arch = "aarch64"
git-tree-sha1 = "c3c5deafeb0f1462c25754afbef9a5c502f8b86a"
os = "macos"

    [[GAP_pkg_orb.download]]
    sha256 = "17643bd798acb1781cc6cf4ac303f40cada95aa2def8056506e14d0f07ef1b2e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v501.10000.1+0/GAP_pkg_orb.v501.10000.1.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_orb]]
arch = "aarch64"
git-tree-sha1 = "a926f7c050eab7199f00b32f4df73a33375f8bde"
libc = "glibc"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "8a9d543982d29367d8a83a34fac4736266c76122846c4f817e95248249f87682"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v501.10000.1+0/GAP_pkg_orb.v501.10000.1.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_orb]]
arch = "aarch64"
git-tree-sha1 = "b5d2cdfbfd4c4e1839b4d7b75c32474c25269d1d"
libc = "musl"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "e4854e5e3c7b42f8fe2da144321a8f94277adb761534ad146932596f07f7c8a1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v501.10000.1+0/GAP_pkg_orb.v501.10000.1.aarch64-linux-musl.tar.gz"
[[GAP_pkg_orb]]
arch = "aarch64"
git-tree-sha1 = "2c12a95f2b0a5b9f5da58ff6fd82162080c87c23"
os = "freebsd"

    [[GAP_pkg_orb.download]]
    sha256 = "6a1a3aff45a1ac91c7b4d6b09ea9bb3d677c11476e9ad8f88329d41c94a158d3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v501.10000.1+0/GAP_pkg_orb.v501.10000.1.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_orb]]
arch = "powerpc64le"
git-tree-sha1 = "f6c993e653c098db51132f8cda8ce4b56c2b6cc4"
libc = "glibc"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "28bc42118ce997ee059c8b97f91be1c53b6aba2557655374abe8667d53ae038e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v501.10000.1+0/GAP_pkg_orb.v501.10000.1.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_orb]]
arch = "riscv64"
git-tree-sha1 = "5c840c27cf7e6d5df1d07a65ac6d72db9b22f7c9"
libc = "glibc"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "1dd1a7287bc365074c85b0f6bb3ed7f63df0f3d37e6fc42936d491115caba4ea"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v501.10000.1+0/GAP_pkg_orb.v501.10000.1.riscv64-linux-gnu.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "ae47b98b0e3331d32d315672dc03151bbe667b9f"
os = "macos"

    [[GAP_pkg_orb.download]]
    sha256 = "3261e139098e0bd1b551459dcee3bf44361f5eb99b1ba6f569afc7805a4f8d8d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v501.10000.1+0/GAP_pkg_orb.v501.10000.1.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "450b84aa28c7cb9bb21471393d5b53f7a650a730"
libc = "glibc"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "477c42096859decf7f839e807979abde948ac3b6ffebc3b8e97abe7c086ec17e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v501.10000.1+0/GAP_pkg_orb.v501.10000.1.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "56a8c0b35f49ef5bc6540a001ba2df16535b46da"
libc = "musl"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "dafb16b28dd2ac802b301351015d0ced646bd7fe20e2f36e3cd5f08f7a8a2da5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v501.10000.1+0/GAP_pkg_orb.v501.10000.1.x86_64-linux-musl.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "21da4fa314d48253f49d0b19adc897005535aab9"
os = "freebsd"

    [[GAP_pkg_orb.download]]
    sha256 = "809a5f27b464b2bb9adb328468ec8795336ebd426fd713901cf9db9ea480f862"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v501.10000.1+0/GAP_pkg_orb.v501.10000.1.x86_64-unknown-freebsd.tar.gz"
