[[GAP_pkg_orb]]
arch = "aarch64"
git-tree-sha1 = "c2faeb2a22a90e94bb5b1ce7df8564b28432acac"
os = "macos"

    [[GAP_pkg_orb.download]]
    sha256 = "33c94b1bdea6c12ed35113820c989ea45866725f10f083964a4d50e1ffeb5ed0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.100+0/GAP_pkg_orb.v400.900.100.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_orb]]
arch = "aarch64"
git-tree-sha1 = "14f0270e23252b526093d12232e8f5ce99b9cbfb"
libc = "glibc"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "e2a2b51a0df2285860efbc6d759b0abcc372f3c04f69b015f5d4db31385a25dd"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.100+0/GAP_pkg_orb.v400.900.100.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_orb]]
arch = "aarch64"
git-tree-sha1 = "ecaad4d40af03cf989aa9c1a963655f0868aea34"
libc = "musl"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "4516aef9d413e3b3debfac2b9d66dc8866a1a3964fbf4c429b01c822b1895f20"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.100+0/GAP_pkg_orb.v400.900.100.aarch64-linux-musl.tar.gz"
[[GAP_pkg_orb]]
arch = "powerpc64le"
git-tree-sha1 = "33571db5ace13ef9a5ad455fb8b7cbeb7cf63b9b"
libc = "glibc"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "d816299410a21bb4eadea44b67f6dac25ad8f69118213a08ad6d061ba6172342"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.100+0/GAP_pkg_orb.v400.900.100.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "e94edd776dd1794c251a2be4043f65fbdd21a100"
os = "macos"

    [[GAP_pkg_orb.download]]
    sha256 = "0072a53ee4040cdd42bd14a10dddd00a397bc8d35b72d9a8d6dcf36c1a5f2b83"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.100+0/GAP_pkg_orb.v400.900.100.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "13c61f6412ba494da1b9fcf83039ddb9888e0474"
libc = "glibc"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "d5466fd763c0e46bb8bc0be8af9e6fd25e1028c90b244f0931dd73dbcdcbd92c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.100+0/GAP_pkg_orb.v400.900.100.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "a3bd1e896a0cc1978269420f9aece653140290f1"
libc = "musl"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "4db21d3b47c13818a5d1e6864b1201bed51a49ebff0e2d860ac9564371910d6c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.100+0/GAP_pkg_orb.v400.900.100.x86_64-linux-musl.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "0fdd18753f782f0ff7abde221987462507efac15"
os = "freebsd"

    [[GAP_pkg_orb.download]]
    sha256 = "fe7c1f512eb1db5b6af8ca66a20142461ca28c58b805f68370a7e30445d4ee17"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.100+0/GAP_pkg_orb.v400.900.100.x86_64-unknown-freebsd.tar.gz"
