[[GAP_pkg_orb]]
arch = "aarch64"
git-tree-sha1 = "dfa238e25bba4072fb99beab76088f0c0ae0e70d"
os = "macos"

    [[GAP_pkg_orb.download]]
    sha256 = "61bd36ac77f74b8273e576c50b3d9263468f76a377fd8ef48312c5c442ec3d0e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.2+0/GAP_pkg_orb.v400.900.2.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_orb]]
arch = "aarch64"
git-tree-sha1 = "6c7a1bb573db6c642ab7bc9f69a453d047a2b61e"
libc = "glibc"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "8655afeb2530c58e13037f00a41723159ee81c5ff8b5e15a82edc47c76b4bf1f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.2+0/GAP_pkg_orb.v400.900.2.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_orb]]
arch = "aarch64"
git-tree-sha1 = "409a6ec4bac1668c1c91f943d22a1def1b1b0ff5"
libc = "musl"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "85ad5c31db9b7972ee1d559f9cbc340e8d8a05be0f55d301cb3b9cd3f21c077a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.2+0/GAP_pkg_orb.v400.900.2.aarch64-linux-musl.tar.gz"
[[GAP_pkg_orb]]
arch = "powerpc64le"
git-tree-sha1 = "16d3d812da38764926d5fb60f087557c44a86390"
libc = "glibc"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "bce98181ba165cb204c932d9982acf39a36299e11f9ff1d2784ac870d340d2d2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.2+0/GAP_pkg_orb.v400.900.2.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "fccc12626e9176fbdd290c9780f3a04d1e85a7b2"
os = "macos"

    [[GAP_pkg_orb.download]]
    sha256 = "253ddea393540022f0553ff55cb96757eb7fe3248c17997e43742378fe115acf"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.2+0/GAP_pkg_orb.v400.900.2.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "4b89968dbdf9158fde56170d7b725449b7c233a3"
libc = "glibc"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "ffde596a046646606796c1c4d29e70b810021bd383801f5754965cf807868ebb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.2+0/GAP_pkg_orb.v400.900.2.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "59fc4bcaf3a3a20c8c6d161a31a8c4a521669fce"
libc = "musl"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "ddd11e89229ec9f5f89203a7d6c3dc1dc3fa60772b2051dfac1f073fdba7cc41"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.2+0/GAP_pkg_orb.v400.900.2.x86_64-linux-musl.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "cef9782654852b538433ac2609ef8fb05e727c55"
os = "freebsd"

    [[GAP_pkg_orb.download]]
    sha256 = "2091bd0fc1924548193243cf74122e1bb17c8bcd0f63cd047b5ec23319fb17f5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.2+0/GAP_pkg_orb.v400.900.2.x86_64-unknown-freebsd.tar.gz"
