[[GAP_pkg_orb]]
arch = "aarch64"
git-tree-sha1 = "971bcbf59df5c4661a5774edfbc2ef82d9d9afc8"
os = "macos"

    [[GAP_pkg_orb.download]]
    sha256 = "92a53ff43ecef1765e176fd706596343d21a0f05b6f03479ebc4293bebb769d8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.1+0/GAP_pkg_orb.v400.900.1.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_orb]]
arch = "aarch64"
git-tree-sha1 = "0cf6d75e701d10a7a02980f4c0f7d69be89d7d19"
libc = "glibc"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "82bcd014dd91bd8bc2ec2a57065e88a69c818bea7ec7eef463bc3d11c0ac50c8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.1+0/GAP_pkg_orb.v400.900.1.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_orb]]
arch = "aarch64"
git-tree-sha1 = "f5b710a0215396b5584171ccd750115dca1d2010"
libc = "musl"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "59c55b9f5960ad0300565677e977ee665617d443433e18aecfd3960dcff697f0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.1+0/GAP_pkg_orb.v400.900.1.aarch64-linux-musl.tar.gz"
[[GAP_pkg_orb]]
arch = "powerpc64le"
git-tree-sha1 = "2ed29dc0908dbb8a30cf999ab203df1a0838d379"
libc = "glibc"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "04b70d3a3b29f7b18f5c1c4d4e60d731e6bd985249a583b23e215532e29da0e7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.1+0/GAP_pkg_orb.v400.900.1.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "65dfcdbf8c7e5fb77fd38eb2973cfdb4664a1106"
os = "macos"

    [[GAP_pkg_orb.download]]
    sha256 = "d56a826399536d4e4318027a2e874bd63080d8d3d27d5956998c8d3e6e8e9133"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.1+0/GAP_pkg_orb.v400.900.1.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "335e921d5db90f00117ac29f2a2ad8c9c677cd32"
libc = "glibc"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "70b2ab1755d0119073cc045f5b5975072815d8bcb1c23754755a88fb5b92634c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.1+0/GAP_pkg_orb.v400.900.1.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "5ecfa96521b351fe74ea2d19cd41de73d654a7ba"
libc = "musl"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "124e408f14418d9e5583a071f07f2aedce6ccae47f246540fed10c7fe255a896"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.1+0/GAP_pkg_orb.v400.900.1.x86_64-linux-musl.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "e20b430131573ef309ac1205300d54af4cc5b6fd"
os = "freebsd"

    [[GAP_pkg_orb.download]]
    sha256 = "8ad36556c8851f1026fa77a9ccecee42eb6f2fc31945a0f788385f785aa679e5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.1+0/GAP_pkg_orb.v400.900.1.x86_64-unknown-freebsd.tar.gz"
