[[GAP_pkg_orb]]
arch = "aarch64"
git-tree-sha1 = "cba5f888bc05f53d93f203fae144d1c45f9827f0"
os = "macos"

    [[GAP_pkg_orb.download]]
    sha256 = "a69ec05ccaa77dd382da471430f5341e91c7cd3498541cfa9afb7d4b749bcd2f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.0+1/GAP_pkg_orb.v400.900.0.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_orb]]
arch = "aarch64"
git-tree-sha1 = "9d41207ddb09359442ae69455937cfcb7d5da913"
libc = "glibc"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "ac74eee3973e9ff270b1abaed2f7262a872d9212807e23c476546be204a71aea"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.0+1/GAP_pkg_orb.v400.900.0.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_orb]]
arch = "aarch64"
git-tree-sha1 = "658a1f3de175ab756da188348fab1bea808d9a25"
libc = "musl"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "29886984b855bdf130adf4686a5dc73ef84e2eb1b579f3d32255b2a8a8901a7b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.0+1/GAP_pkg_orb.v400.900.0.aarch64-linux-musl.tar.gz"
[[GAP_pkg_orb]]
arch = "powerpc64le"
git-tree-sha1 = "4d5f999f8f2c81726d10836c84c54ecf3be7af8d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "c49f879a507db30080deb2d46041d96da042b7dd1d25f6304158e464d3320a0a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.0+1/GAP_pkg_orb.v400.900.0.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "8a576d0cd0a2056c3ac9239a136507afcf68c0ea"
os = "macos"

    [[GAP_pkg_orb.download]]
    sha256 = "07c00a93a0a00aae17a7e7c0d117b086009fcfe37b7ed042f2df1393d9610ef9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.0+1/GAP_pkg_orb.v400.900.0.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "f95533ac3eaec431e524c5ae3c4cfa70c629b492"
libc = "glibc"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "36e8ab86fdf1387dc3c7b05125fce5bb2698673d069bd5a11cceacec059e8ff2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.0+1/GAP_pkg_orb.v400.900.0.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "5beabc19f8cd61a881f184d37b1eb34b26b3f871"
libc = "musl"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "5efc78729417864b969da745dad8944ff407605d11cea3378b25c438ddd77ac7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.0+1/GAP_pkg_orb.v400.900.0.x86_64-linux-musl.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "e20b430131573ef309ac1205300d54af4cc5b6fd"
os = "freebsd"

    [[GAP_pkg_orb.download]]
    sha256 = "8ad36556c8851f1026fa77a9ccecee42eb6f2fc31945a0f788385f785aa679e5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.0+1/GAP_pkg_orb.v400.900.0.x86_64-unknown-freebsd.tar.gz"
