[[GAP_pkg_orb]]
arch = "aarch64"
git-tree-sha1 = "ffe0efafa8b1c0701a54968b1d173bd55a738179"
os = "macos"

    [[GAP_pkg_orb.download]]
    sha256 = "1d5a9fd016ca78dc59c984978405637da5d8a5b69f281099335a6e6aa6fa1a22"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.102+0/GAP_pkg_orb.v400.900.102.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_orb]]
arch = "aarch64"
git-tree-sha1 = "f22a2a1502b996f08a798118ddc0e36e9ff8e7c6"
libc = "glibc"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "79bfad3466a1090bc0d1ac4a3a68fb6423319fdb10d208d8e03979d006cdcf4a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.102+0/GAP_pkg_orb.v400.900.102.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_orb]]
arch = "aarch64"
git-tree-sha1 = "299a6b41f85d506a08904ef8a831442838cf754c"
libc = "musl"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "5c75c6aa07c620f7918a10ca2f66d7401f7f057125686798ff9594170c82f91b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.102+0/GAP_pkg_orb.v400.900.102.aarch64-linux-musl.tar.gz"
[[GAP_pkg_orb]]
arch = "aarch64"
git-tree-sha1 = "1fca18560c39d101d321327641797606017c3ed8"
os = "freebsd"

    [[GAP_pkg_orb.download]]
    sha256 = "b26ce7506d3a043de36638a31fcd338dbc8d9ff4154c3616395b56a16bd63c3b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.102+0/GAP_pkg_orb.v400.900.102.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_orb]]
arch = "powerpc64le"
git-tree-sha1 = "45d5fa8a25b7c31a4215dc754e27524cc2907e4e"
libc = "glibc"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "dfa2b7250df21b97e6e73df6521fb18c95dd29e0b456bf82070076a9b4b05fd7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.102+0/GAP_pkg_orb.v400.900.102.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_orb]]
arch = "riscv64"
git-tree-sha1 = "183f594d24b983c450844973468403dd9356ec61"
libc = "glibc"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "f6b83636178c5ffcb6b848e3ca24e6dce7c8c00aace5b3d23fbd06734b0ba87c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.102+0/GAP_pkg_orb.v400.900.102.riscv64-linux-gnu.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "af3059d131d3a03c7bc9860afa6a664fc297485d"
os = "macos"

    [[GAP_pkg_orb.download]]
    sha256 = "c39c4ad8c640ed609c4a548ed259b1f76594ff02ef2ed819ac072379a3dcdc3c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.102+0/GAP_pkg_orb.v400.900.102.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "e2c151956f399295f75316f14845e297cd74291e"
libc = "glibc"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "723596d4a36ec2e678ae0e586bc72cd9a0a338c2b73ab737350cb92d60c8a2d2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.102+0/GAP_pkg_orb.v400.900.102.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "90a456adfcd642f8c25e7bb4b472adb7b934d381"
libc = "musl"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "763959348f40cdd30bb20163d5564b635bd3c222f5f3b1f4c73c3610901a15e1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.102+0/GAP_pkg_orb.v400.900.102.x86_64-linux-musl.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "27566da4a270ec4042c1e203a205842126d08688"
os = "freebsd"

    [[GAP_pkg_orb.download]]
    sha256 = "65c2f61791a4407ad43dbb826948e818a7605619e621a4f8a77f16c291497034"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.102+0/GAP_pkg_orb.v400.900.102.x86_64-unknown-freebsd.tar.gz"
