[[GAP_pkg_orb]]
arch = "aarch64"
git-tree-sha1 = "1a8e28e609af4ff73d5f85fce2a99b59a330bd36"
os = "macos"

    [[GAP_pkg_orb.download]]
    sha256 = "8e360f0e42bc431634779d8ebeeed50e40137a209f0ad4c72dae6c24df5c8580"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.100+1/GAP_pkg_orb.v400.900.100.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_orb]]
arch = "aarch64"
git-tree-sha1 = "3091f864a05320421a18a96c72ae0aa59b40c973"
libc = "glibc"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "7e27b5276a11c67cf66aee5961a3416f032286dff3fe0fc84af72895cdbd69a4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.100+1/GAP_pkg_orb.v400.900.100.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_orb]]
arch = "aarch64"
git-tree-sha1 = "0947cf0d5328b23eda1e3b667fbea53c16a3d39d"
libc = "musl"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "98d7afed42aa0fe160c9ce4619a97d018c829ed8fc23fbaf018f6b843685ea83"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.100+1/GAP_pkg_orb.v400.900.100.aarch64-linux-musl.tar.gz"
[[GAP_pkg_orb]]
arch = "powerpc64le"
git-tree-sha1 = "9dea3118c25d35b77fcf00e281cc7fc3eda21cf1"
libc = "glibc"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "bdf043c870cb7cce3b8325168d3de45631dd7cc21f43bf7900952c71270dbc06"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.100+1/GAP_pkg_orb.v400.900.100.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "357359444c80602e15344ba4b6832a44fa1b9cc3"
os = "macos"

    [[GAP_pkg_orb.download]]
    sha256 = "0754c6ba188ed1daf19281ef5d5205111889c44940509376991ab38aebecaa17"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.100+1/GAP_pkg_orb.v400.900.100.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "21e146e36521e5b5bf11e0c9653a4500f50f3f13"
libc = "glibc"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "c0d958a12a5f032ff5f9a321223b94d7fc3ad3c848b00444bc7b66b7fe988679"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.100+1/GAP_pkg_orb.v400.900.100.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "aa88edd3b0b6bcaa3fc52e4114b0599face4a926"
libc = "musl"
os = "linux"

    [[GAP_pkg_orb.download]]
    sha256 = "c51240d81232f3633c42d44f8763d14ba3ab196d3c2b6afaeb493e8d9f942741"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.100+1/GAP_pkg_orb.v400.900.100.x86_64-linux-musl.tar.gz"
[[GAP_pkg_orb]]
arch = "x86_64"
git-tree-sha1 = "12b6107e709c86b4f87321f7a5f9b36bb99b25a9"
os = "freebsd"

    [[GAP_pkg_orb.download]]
    sha256 = "57b0ae6e4c129161c9963a368088121048c750600c7af0f8c16504afb34af95c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_orb_jll.jl/releases/download/GAP_pkg_orb-v400.900.100+1/GAP_pkg_orb.v400.900.100.x86_64-unknown-freebsd.tar.gz"
